---
# Default variables for the vim role
vim_plug_url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
# Repo de dotfiles (personaliza a tu repositorio)
dotfiles_repo: git@github.com:jorgearma1982/dotfiles.git
