---
# Default variables for the vim role
vim_plug_url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
# Repo de dotfiles (personaliza a tu repositorio)
dotfiles_repo: git@github.com:jorgearma1982/dotfiles.git

# Spell check settings: idiomas a descargar (código ISO usados por vim)
spell_languages:
  - en
  - es
# Base URL para archivos de spell de Vim (mirror más fiable)
spell_base_url: https://ftp.nluug.nl/pub/vim/runtime/spell
